//* This file is written on basis of the MOOSE framework
//* File written by Akshay Dandekar, contact: adandeka@purdue.edu
//*
#include "ComputeKelvinVoigtViscousHeatEnergy.h"
#include "libmesh/utility.h"

registerMooseObject("HeatConductionApp", ComputeKelvinVoigtViscousHeatEnergy);

template <>
InputParameters
validParams<ComputeKelvinVoigtViscousHeatEnergy>()
{
  InputParameters params = validParams<Material>();
  params.addParam<std::string>("base_name",
                               "Optional parameter that allows the user to define "
                               "multiple mechanics material systems on the same "
                               "block, i.e. for multiple phases");
  params.addClassDescription("Heat energy density generated by viscous dissipation (Tauchert 1967)");
  return params;
}

ComputeKelvinVoigtViscousHeatEnergy::ComputeKelvinVoigtViscousHeatEnergy(const InputParameters & parameters)
  : DerivativeMaterialInterface<Material>(parameters),
    _base_name(isParamValid("base_name") ? getParam<std::string>("base_name") + "_" : ""),
    _stress(getMaterialPropertyByName<RankTwoTensor>("stress")),
    _strain_rate(getMaterialPropertyByName<RankTwoTensor>("strain_rate")),
    _heat_source_rate(declareProperty<Real>("heat_source_rate"))
{
}

void
ComputeKelvinVoigtViscousHeatEnergy::computeQpProperties()
{
  _heat_source_rate[_qp] = 0.0;

  for (unsigned int i = 0; i < LIBMESH_DIM; ++i) {
    for (unsigned int j = 0; j < LIBMESH_DIM; ++j) {
      _heat_source_rate[_qp] += _stress[_qp](i,j) * _strain_rate[_qp](i,j);
    }
  }

  if (_heat_source_rate[_qp] < 0.0) {
    _heat_source_rate[_qp] = 0.0;
  }

}
